//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagementClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagementService")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAvailableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAvailable {
            get {
                return this.IsAvailableField;
            }
            set {
                if ((this.IsAvailableField.Equals(value) != true)) {
                    this.IsAvailableField = value;
                    this.RaisePropertyChanged("IsAvailable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagementService")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> ErrorsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Errors {
            get {
                return this.ErrorsField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorsField, value) != true)) {
                    this.ErrorsField = value;
                    this.RaisePropertyChanged("Errors");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryManagementClient.ServiceReference1.ValidationFault), Action="http://tempuri.org/IService1/AddBookValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagementService")]
        void AddBook(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddBook", ReplyAction="http://tempuri.org/IService1/AddBookResponse")]
        System.Threading.Tasks.Task AddBookAsync(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveBook", ReplyAction="http://tempuri.org/IService1/RemoveBookResponse")]
        void RemoveBook(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveBook", ReplyAction="http://tempuri.org/IService1/RemoveBookResponse")]
        System.Threading.Tasks.Task RemoveBookAsync(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(LibraryManagementClient.ServiceReference1.ValidationFault), Action="http://tempuri.org/IService1/UpdateBookValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/LibraryManagementService")]
        void UpdateBook(LibraryManagementClient.ServiceReference1.Book book, LibraryManagementClient.ServiceReference1.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBook", ReplyAction="http://tempuri.org/IService1/UpdateBookResponse")]
        System.Threading.Tasks.Task UpdateBookAsync(LibraryManagementClient.ServiceReference1.Book book, LibraryManagementClient.ServiceReference1.Book newBook);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBooks", ReplyAction="http://tempuri.org/IService1/GetAllBooksResponse")]
        System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> GetAllBooks();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBooks", ReplyAction="http://tempuri.org/IService1/GetAllBooksResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> GetAllBooksAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBookByISBN", ReplyAction="http://tempuri.org/IService1/LookupBookByISBNResponse")]
        LibraryManagementClient.ServiceReference1.Book LookupBookByISBN(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBookByISBN", ReplyAction="http://tempuri.org/IService1/LookupBookByISBNResponse")]
        System.Threading.Tasks.Task<LibraryManagementClient.ServiceReference1.Book> LookupBookByISBNAsync(string ISBN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBooksByTitle", ReplyAction="http://tempuri.org/IService1/LookupBooksByTitleResponse")]
        System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> LookupBooksByTitle(string Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBooksByTitle", ReplyAction="http://tempuri.org/IService1/LookupBooksByTitleResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> LookupBooksByTitleAsync(string Title);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBooksByAuthor", ReplyAction="http://tempuri.org/IService1/LookupBooksByAuthorResponse")]
        System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> LookupBooksByAuthor(string Author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/LookupBooksByAuthor", ReplyAction="http://tempuri.org/IService1/LookupBooksByAuthorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> LookupBooksByAuthorAsync(string Author);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckBookAvailability", ReplyAction="http://tempuri.org/IService1/CheckBookAvailabilityResponse")]
        bool CheckBookAvailability(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CheckBookAvailability", ReplyAction="http://tempuri.org/IService1/CheckBookAvailabilityResponse")]
        System.Threading.Tasks.Task<bool> CheckBookAvailabilityAsync(LibraryManagementClient.ServiceReference1.Book book);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookAvailability", ReplyAction="http://tempuri.org/IService1/UpdateBookAvailabilityResponse")]
        void UpdateBookAvailability(LibraryManagementClient.ServiceReference1.Book book, bool isAvailable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateBookAvailability", ReplyAction="http://tempuri.org/IService1/UpdateBookAvailabilityResponse")]
        System.Threading.Tasks.Task UpdateBookAvailabilityAsync(LibraryManagementClient.ServiceReference1.Book book, bool isAvailable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksByAvailability", ReplyAction="http://tempuri.org/IService1/GetBooksByAvailabilityResponse")]
        System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> GetBooksByAvailability(bool isAvailable);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBooksByAvailability", ReplyAction="http://tempuri.org/IService1/GetBooksByAvailabilityResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> GetBooksByAvailabilityAsync(bool isAvailable);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : LibraryManagementClient.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<LibraryManagementClient.ServiceReference1.IService1>, LibraryManagementClient.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddBook(LibraryManagementClient.ServiceReference1.Book book) {
            base.Channel.AddBook(book);
        }
        
        public System.Threading.Tasks.Task AddBookAsync(LibraryManagementClient.ServiceReference1.Book book) {
            return base.Channel.AddBookAsync(book);
        }
        
        public void RemoveBook(LibraryManagementClient.ServiceReference1.Book book) {
            base.Channel.RemoveBook(book);
        }
        
        public System.Threading.Tasks.Task RemoveBookAsync(LibraryManagementClient.ServiceReference1.Book book) {
            return base.Channel.RemoveBookAsync(book);
        }
        
        public void UpdateBook(LibraryManagementClient.ServiceReference1.Book book, LibraryManagementClient.ServiceReference1.Book newBook) {
            base.Channel.UpdateBook(book, newBook);
        }
        
        public System.Threading.Tasks.Task UpdateBookAsync(LibraryManagementClient.ServiceReference1.Book book, LibraryManagementClient.ServiceReference1.Book newBook) {
            return base.Channel.UpdateBookAsync(book, newBook);
        }
        
        public System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> GetAllBooks() {
            return base.Channel.GetAllBooks();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> GetAllBooksAsync() {
            return base.Channel.GetAllBooksAsync();
        }
        
        public LibraryManagementClient.ServiceReference1.Book LookupBookByISBN(string ISBN) {
            return base.Channel.LookupBookByISBN(ISBN);
        }
        
        public System.Threading.Tasks.Task<LibraryManagementClient.ServiceReference1.Book> LookupBookByISBNAsync(string ISBN) {
            return base.Channel.LookupBookByISBNAsync(ISBN);
        }
        
        public System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> LookupBooksByTitle(string Title) {
            return base.Channel.LookupBooksByTitle(Title);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> LookupBooksByTitleAsync(string Title) {
            return base.Channel.LookupBooksByTitleAsync(Title);
        }
        
        public System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> LookupBooksByAuthor(string Author) {
            return base.Channel.LookupBooksByAuthor(Author);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> LookupBooksByAuthorAsync(string Author) {
            return base.Channel.LookupBooksByAuthorAsync(Author);
        }
        
        public bool CheckBookAvailability(LibraryManagementClient.ServiceReference1.Book book) {
            return base.Channel.CheckBookAvailability(book);
        }
        
        public System.Threading.Tasks.Task<bool> CheckBookAvailabilityAsync(LibraryManagementClient.ServiceReference1.Book book) {
            return base.Channel.CheckBookAvailabilityAsync(book);
        }
        
        public void UpdateBookAvailability(LibraryManagementClient.ServiceReference1.Book book, bool isAvailable) {
            base.Channel.UpdateBookAvailability(book, isAvailable);
        }
        
        public System.Threading.Tasks.Task UpdateBookAvailabilityAsync(LibraryManagementClient.ServiceReference1.Book book, bool isAvailable) {
            return base.Channel.UpdateBookAvailabilityAsync(book, isAvailable);
        }
        
        public System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book> GetBooksByAvailability(bool isAvailable) {
            return base.Channel.GetBooksByAvailability(isAvailable);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<LibraryManagementClient.ServiceReference1.Book>> GetBooksByAvailabilityAsync(bool isAvailable) {
            return base.Channel.GetBooksByAvailabilityAsync(isAvailable);
        }
    }
}
